<?php

/**
 * @file
 * Manage the postcode of both authenticated and anonymous users.
 */

function postcode_get_postcode() {

  $result = '';

  if ( user_is_logged_in() ) {

    global $user;
    $profile = profile2_load_by_user( $user, 'main' );
dsm( $profile );
    if ( ! empty( $profile->field_postcode['und'][0]['safe_value'] ) ) {
      $result = $profile->field_postcode['und'][0]['safe_value'];
    }
  }
  else if ( ! empty($_SESSION['postcode']['postcode']) ) {
    $result = $_SESSION['postcode']['postcode'];
  }

  return $result;
}

function postcode_get_radius() {

  // Default radius. Units controlled elsewhere!
  $result = 5;

  if ( user_is_logged_in() ) {

    global $user;
    $profile = profile2_load_by_user( $user, 'main' );

    if ( ! empty( $profile->field_postcode_radius['und'][0]['safe_value'] ) ) {
      $result = $profile->field_postcode_radius['und'][0]['safe_value'];
    }
  }
  else if ( ! empty($_SESSION['postcode']['radius']) ) {
    $result = $_SESSION['postcode']['radius'];
  }
}

function postcode_exists() {
  $postcode = postcode_get_postcode();
  return ! empty( $postcode );
}

function postcode_is_real_postcode( $pc ) {
  // @todo validate
  return TRUE;
}

function postcode_set_guest_postcode( $pc ) {
  $_SESSION['postcode']['postcode'] = $pc;
  dsm( 'Postcode has been set to ' . $pc );
}

function postcode_preprocess_page( &$variables ) {
  $variables['postcode'] = postcode_get_postcode();
  $variables['postcode_radius'] = postcode_get_radius() . t( ' miles' );
}
