<?php

/**
 * @file
 * Show a modal overlay asking for postcode/login/signup
 */

function loc_popup_init() {

  $is_postcode_needed =
    ! user_is_logged_in()  &&  empty($_SESSION['loc_popup']['postcode']);

  if ( $is_postcode_needed ) {
    // loc_popup_show_overlay();
  }
}

function loc_popup_theme() {
  return array(
    'loc_popup_overlay' => array(
      'variables' => array(
        'close_button' => NULL,
        'postcode_form' => NULL,
        'login_form' => NULL,
        'register_form' => NULL,
      ),
      'template' => 'loc-popup-overlay',
    ),
  );
}

function loc_popup_block_info() {
  return array(
    'postcode' => array(
      'info' => 'Localitee overlay',
    ),
  );
}

function loc_popup_block_view( $delta ) {

  switch ( $delta ) {

  case 'postcode' :
    $is_postcode_needed =
      ! user_is_logged_in()  &&  empty($_SESSION['loc_popup']['postcode']);

    if ( $is_postcode_needed ) {

      drupal_add_js(
        'jQuery(document).ready(function(){ jQuery("#frontModal").modal({keyboard:false}) });',
        array('type' => 'inline', 'scope' => 'footer')
      );

      return array(
        'content' => theme( 'loc_popup_overlay', array(
          'close_button' => drupal_get_form( 'loc_popup_close_button' ),
          'postcode_form' => drupal_get_form( 'loc_popup_postcode_form' ),
          //'login_form' => drupal_get_form( 'loc_popup_login_form' ),
          'login_form' => drupal_get_form( 'user_login' ),
          'register_form' => drupal_get_form( 'loc_popup_register_form' ),
        ) ),
      );
    }
  }
}

function loc_popup_close_button() {

  return array(
    // <button type="button" class="close" data-dismiss="modal">×</button>
    'close-button' => array(
      '#type' => 'submit',
      '#value' => 'x',
      '#attributes' => array(
        'class' => array( 'close' ),
        'data-dismiss' => 'modal',
      ),
    ),
  );
}

function loc_popup_close_button_submit() {
}

function loc_popup_postcode_form( $form, &$form_state ) {
  return array(
    'postcode' => array(
      '#type' => 'textfield',
      '#title' => t('Enter your postcode'),
      '#attributes' => array( 'placeholder' => t('Enter postcode') ),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Go'),
    ),
  );
}

function loc_popup_postcode_form_submit( $form, &$form_state ) {

  $_SESSION['loc_popup']['postcode'] = $form_state['values']['postcode'];
}

function loc_popup_form_user_login_alter( &$form, &$form_state ) {
  // Make any changes to user login form here
}

function loc_popup_register_form( $form, &$form_state ) {
}

function loc_popup_register_form_submit( $form, &$form_state ) {

}

