<?php

/**
 * @file
 * Show a modal overlay asking for postcode/login/signup
 */

function loc_popup_theme() {
  return array(
    'loc_popup_overlay' => array(
      'variables' => array(
        'close_button' => NULL,
        'postcode_form' => NULL,
        'login_form' => NULL,
      ),
      'template' => 'loc-popup-overlay',
    ),
  );
}

function loc_popup_block_info() {
  return array(
    'postcode' => array(
      'info' => 'Localitee overlay',
    ),
  );
}

function loc_popup_is_postcode_input_required() {
  return ( ! user_is_logged_in()  &&
    empty($_SESSION['loc_popup']['postcode']) );
}

function loc_popup_block_view( $delta ) {

  switch ( $delta ) {

  case 'postcode' :

    if ( ! user_is_logged_in()  &&
      ! empty($_SESSION['loc_popup']['postcode']) ) {
      dsm( 'postcode: ' . $_SESSION['loc_popup']['postcode'] );
    }

    if ( loc_popup_is_postcode_input_required() ) {

      // Set postcode so that links from overlay can be followed without
      // the overlay popping up again.
      $_SESSION['loc_popup']['postcode'] = '(Set postcode)';

      return array(
        'content' => theme( 'loc_popup_overlay', array(
          'close_button' => drupal_get_form( 'loc_popup_close_button' ),
          'postcode_form' => drupal_get_form( 'loc_popup_postcode_form' ),
          //'login_form' => drupal_get_form( 'loc_popup_login_form' ),
          'login_form' => drupal_get_form( 'user_login' ),
        ) ),
      );
    }
  }
}

function loc_popup_close_button() {

  return array(
    // <button type="button" class="close" data-dismiss="modal">×</button>
    'close-button' => array(
      '#type' => 'submit',
      '#value' => 'x',
      '#attributes' => array(
        'class' => array( 'close' ),
        'data-dismiss' => 'modal',
      ),
    ),
  );
}

function loc_popup_close_button_submit() {

  // EMPTY - Nothing to do here
  // Postcode was set to '<none>' before overlay was displayed.
}

function loc_popup_postcode_form( $form, &$form_state ) {
  return array(
    'postcode' => array(
      '#type' => 'textfield',
      '#title' => t('Enter your postcode'),
      '#attributes' => array( 'placeholder' => t('Enter postcode') ),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Go'),
    ),
  );
}

function loc_popup_postcode_form_submit( $form, &$form_state ) {

  $_SESSION['loc_popup']['postcode'] = $form_state['values']['postcode'];
}

function loc_popup_form_user_login_alter( &$form, &$form_state ) {
  // Make any changes to user login form here
}

function loc_popup_preprocess_page( &$variables ) {

  if ( ! empty($_SESSION['loc_popup']['postcode']) ) {
    $variables['postcode'] = $_SESSION['loc_popup']['postcode'];
  }
  else {
    $variables['postcode'] = t( '(Set postcode)' );
  }

  if ( ! user_is_logged_in() ) {
    $variables['login_form'] = drupal_get_form( 'user_login' );
  }
}
