<?php

/**
 * @file
 * Show a modal overlay asking for postcode/login/signup
 */

function lt_overlay_menu() {
  return array(
    'guest' => array(
      'description' => 'Options for guests',
      'access callback' => 'user_is_anonymous',
      'title' => 'Guest options',
      'page callback' => '_lt_guest_options_page',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

function _lt_guest_options_page() {
  global $user;

  // Is the current user logged in?
  if ( $user->uid > 0 ) {
    // Got to the page for editing postcode anbd radius settings.
    drupal_goto( 'user/' . $user->uid . '/edit/main' );
  }
  else {
    return drupal_get_form( 'postcode_form' );
  }
}

function lt_overlay_should_show() {
  return
    user_is_anonymous() &&
    ! postcode_exists() &&
    arg(0) != 'user' &&
    arg(0) != 'guest'
    ;
}

function lt_overlay_preprocess_page( &$variables ) {

  $should_show = lt_overlay_should_show();
  $variables['lt_overlay']['show it?'] = $should_show;

  if ( $should_show ) {
    $variables['lt_overlay']['postcode_form'] =
      drupal_get_form( 'postcode_form' );
    $variables['lt_overlay']['login_form'] =
      drupal_get_form( 'user_login' );
  }
}


function lt_overlay_form_user_login_alter( &$form, &$form_state ) {
  //$form['#validate'][] = 'lt_overlay_user_login_validate';
  //$form['#submit'][] = 'lt_overlay_user_login_submit';
}

/*
function lt_overlay_user_login_validate( $form, &$form_state ) {
}

function lt_overlay_user_login_submit( $form, &$form_state ) {
}
*/
