<?php

/**
 * @file
 * Show a modal overlay asking for postcode/login/signup
 */

/**
 * Implements hook_preprocess_page()
 */
function lt_misc_preprocess_page( &$variables ) {

  // Not sure if this is still required.
  // It was for putting the login form in the "account" management button.
  if ( ! user_is_logged_in() ) {
    $variables['login_form'] = drupal_get_form( 'user_login' );
  }

  // Does the current page represent a node?
  if ( !empty( $variables['node']->type ) ) {
    // Allow the page template to be overriden by one specific to the
    // type of the current node.
    $variables['theme_hook_suggestions'][] =
      'page__node_' . $variables['node']->type;
  }
}

function lt_misc_views_query_alter( &$view, &$query ) {

   if ( ! empty($view->filter['flat']) ) {
  $bounds_calculator = new openlayers_proximity_handler_filter_square();
  $bounds = $bounds_calculator->get_bounds( 53.359058, -2.038366, 5 );
  dsm( $bounds );
dsm( $query );
   print( "<pre>" );
   print_object_route( $query, '53' );
   print( "</pre>" );
  }
}

function print_object_route( $object, $text, $depth=0 ) {
  if ( $depth > 20 ) {
    return FALSE;
  }

  $array = NULL;

  if ( is_object( $object ) ) {
    //dsm( 'got an object' );
    $array = get_object_vars( $object );
    //dsm( $array );
  }
  elseif ( is_array( $object ) ) {
    //dsm( 'got an array' );
    $array = $object;
  }
  elseif ( strpos( strval($object), $text ) !== FALSE ) {
    //dsm( 'win! got the text' );
    print_object_node( $object, $depth );
    return TRUE;
  }
  else {
    //dsm( 'lose :( end of the line' );
    return FALSE;
  }

  $success = FALSE;
  foreach ( $array as $key => $val  ) {

    if ( strval( $key ) != 'view'  &&
      ( strpos( strval($key), $text ) !== FALSE  ||
      print_object_route( $val, $text, $depth+1 ) ) ) {

        print_object_node( $key, $depth );
        $success = TRUE;
    }
  }
  return $success;
}

function print_object_node( $text, $depth ) {
  $spaces = '';
  if ( $depth > 0 ) {
    $depth += 2;
    for ( $i=0; $i < $depth; $i++ ) {
      $spaces .= '&nbsp;';
    }
  }
  else {
    $spaces .= '* ';
  }

  print $spaces . strval( $text ) . '<br />';
}


